---
title: "Election Predicition"
author: "Samuel Lowry"
date: "11/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#needed packages
library(tidyverse)
library(lubridate)
library(janitor)
library(ggthemes)
library(survey)
library(usmap)
library(jtools)
library(caret)
library(huxtable)
library(gt)
```

Poll by state

```{r}
#https://data.fivethirtyeight.com
#538 poll data
polls_df <- read_csv("../data/polls/president_polls.csv") %>% 
  #not considering split states for project
  filter(!state %in% c("Maine CD-1", "Maine CD-2", "Nebraska CD-1", "Nebraska CD-2"),
         stage == "general",
         answer %in% c("Trump", "Biden"),
         #get rid of non C and up polls
         !fte_grade %in% c("D+", "D", "D-", "F", "")) %>%
  #no not graded polls
  drop_na(fte_grade) %>%
  #weights so that A is 3x as C and B is 2x
  mutate(weight = case_when(fte_grade %in% c("A+", "A", "A-", "A/B") ~ 3,
                            fte_grade %in% c("B+", "B", "B-", "B/C") ~ 2,
                            fte_grade %in% c("C+", "C", "C-", "C/D") ~ 1)) %>% 
  mutate(end_date = mdy(end_date),
         election_date = mdy(election_date)) %>% 
  mutate(days_out = as.duration(interval(end_date, election_date)) / (60*60*24)) %>% 
  #75 days out coincides with end of democratic convention
  filter(days_out <= 75) %>% 
  #weighting for how recent they are. Two weeks out are 3x convention time polls
  mutate(weight = case_when(days_out <= 14 ~ weight * 3, 
                            days_out <= 28 & days_out > 14 ~ weight * 2,
                            days_out > 28 ~ weight * 1)) %>% 
  group_by(state, answer) %>% 
  nest()%>%
  mutate(n = map_dbl(data, nrow)) %>% 
  #get rid of states without more than 2 reliable polls for weighting
  filter (n >= 2) %>% 
  unnest() 


#don't have Wyoming, Rhode Island, Tennessee, District of Columbia, Nebraska
# but have survey monkey polls so this is what we have got 
#relient on survey monkey for these states. luckily these states are pretty solid
bad_polls_df <- read_csv("../data/polls/president_polls.csv") %>% 
    filter(state %in% c("Wyoming", "Rhode Island", "Tennessee", "District of Columbia", "Nebraska",
                        "Alabama", "Connecticut", "Delaware", "Hawaii", "Idaho", "South Dakota",
                        "West Virginia", "Illinois"),
           stage == "general",
           answer %in% c("Trump", "Biden")) %>% 
  drop_na(fte_grade) %>% 
  #weighting for how recent they are. Two weeks out are 3x convention time polls
  mutate(weight = case_when(fte_grade %in% c("B+", "B", "B-", "B/C") ~ 2,
                            TRUE~ 1)) %>% 
  mutate(end_date = mdy(end_date),
         election_date = mdy(election_date)) %>% 
  mutate(days_out = as.duration(interval(end_date, election_date)) / (60*60*24)) %>% 
  filter(days_out <= 75) %>% 
  mutate(weight = case_when(days_out <= 14 ~ weight * 3, 
                            days_out <= 28 & days_out > 14 ~ weight * 2,
                            days_out > 28 ~ weight * 1))
```

```{r}
#join the reliable and unreliable polls
pred_df <- polls_df %>% 
  rbind(bad_polls_df)

#weighted means using survey package
poll_pred <- pred_df %>% 
  group_by(state, answer) %>% 
  nest() %>% 
  #used survey package to assign weights
  mutate(weighted_data = map(data, ~svydesign(id = ~1, weights = ~weight, data = .x))) %>% 
  #used it again to get estimates
  mutate(estimates = map(weighted_data, ~as.data.frame(svymean(~pct, .x)))) %>% 
  unnest(cols = estimates) %>% 
  rename(sd = pct) %>% 
  mutate(high = mean + (2 * sd),
         low = mean - (2 * sd))

#spliting up to get one row per state
trump_poll_pred <- poll_pred %>% 
  filter(answer == "Trump")

biden_poll_pred <- poll_pred %>% 
  filter(answer == "Biden")

#combine for one row per state
wide_poll_pred <- trump_poll_pred %>% 
  full_join(biden_poll_pred,
            by = "state",
            suffix = c("_trump", "_biden")) %>%
  select(state, mean_trump, mean_biden) %>% 
  mutate(dif_trump = mean_trump - mean_biden) %>% 
  #creating factor columns
  mutate(map = case_when(dif_trump > 10 ~ "Solid Trump",
                         dif_trump > 5 & dif_trump < 10 ~ "Lean Trump",
                         dif_trump < 5 & dif_trump > -5 ~ "Toss-Up",
                         dif_trump < -10 ~ "Solid Biden",
                         dif_trump < -5 & dif_trump > -10 ~ "Lean Biden")) %>% 
  mutate(map = factor(map, levels = c("Solid Trump", "Lean Trump", "Toss-Up", "Lean Biden", "Solid Biden")))

#map based upon factor columns 
plot_usmap(data = wide_poll_pred, regions = "states", values = "map", color = "black") +
  scale_fill_manual(values = c("red4","red", "purple", "blue", "blue4"), name = "Election Outcome") +
  labs(title = "2020 Presidential Election Poll-Based Prediction",
       subtitle = "Utilizing weighted polls since the end of the conventions") +
  theme_void() +
  theme(plot.title = element_text(face = "bold", size = 20)) +
  theme(plot.subtitle = element_text(size = 15),
        strip.text = element_text(colour = 'black')) +
   theme(legend.title = element_text(size = 13, face = "bold"),
        legend.text = element_text(size = 11))

#save plot
ggsave("../figures/polls_plot.png", height = 4.5)
```

National poll estimate

```{r}
national_polls_df <- polls_df %>% 
  filter(is.na(state))

#replicate rows for weights
#https://stackoverflow.com/questions/38499032/repeat-the-rows-in-a-data-frame-based-on-values-in-a-specific-column
national_polls_df <- national_polls_df[rep(seq(nrow(national_polls_df)), national_polls_df$weight),]
#sd of .109 for both Biden and Trump from earlier

vep_df <- read_csv("../data/vep_1980-2016.csv") %>% 
  filter(state == "United States")

pvstate_df <- read_csv("../data/popvote_bystate_1948-2016.csv") %>% 
  filter(year > 1967) %>% 
  group_by(year) %>% 
  summarize(D = sum(D),
            R = sum(R))

popvote_df <- read_csv("../data/popvote_1948-2016.csv")

historic_polls_df <- read_csv("../data/pollavg_1968-2016.csv")

poll_vep_df <- popvote_df %>% 
  inner_join(historic_polls_df %>%  filter(days_left < 75)) %>% 
  inner_join(vep_df) %>% 
  left_join(pvstate_df)

polls_dem20_df <- national_polls_df %>% 
  filter(answer == "Biden")

polls_rep20_df <-  national_polls_df %>% 
  filter(answer == "Trump")

# VEP used for 2020
VEP <- as.integer(vep_df$VEP[vep_df$state == "United States" & vep_df$year == 2016])

# Simulating a distribution of election results for Michigan 2020
National_R <- poll_vep_df %>%
  filter(party=="republican") %>% 
  mutate(prob_poll = avg_support/100)

#sd for poll dist
SD_R <- sd(polls_rep20_df$pct)/100

National_D <- poll_vep_df %>%
  filter(party =="democrat") %>% 
  mutate(prob_poll = avg_support/100)

#sd for poll dist
SD_D <- sd(polls_dem20_df$pct)/100

# Trump and Biden models
R_glm <- glm(cbind(R, VEP-R) ~ avg_support, National_R, family = binomial)
D_glm <- glm(cbind(D, VEP-D) ~ avg_support, National_D, family = binomial)

# Predictions for both trump and Biden
# numbers from pol pred I made above
prob_Rvote_2020 <- predict(R_glm, newdata = data.frame(avg_support = 42.25), type="response")[[1]]
prob_Dvote_2020 <- predict(D_glm, newdata = data.frame(avg_support = 51.25), type="response")[[1]]

## Get predicted distribution of draws from the population
sim_Rvotes_2020 <- rbinom(n = 10000, size = VEP, prob = rnorm(10000, mean = prob_Rvote_2020, sd = SD_R))
sim_Dvotes_2020 <- rbinom(n = 10000, size = VEP, prob = rnorm(10000, mean = prob_Dvote_2020, sd = SD_D))

## Simulating a distribution of election results
biden_elxns_2020 <- tibble(votes = sim_Dvotes_2020,
                           VEP = sim_Dvotes_2020+sim_Rvotes_2020) %>%
  mutate(pct = (votes/VEP)*100,
         Candidate = "Biden")

trump_elxns_2020 <- tibble(votes = sim_Rvotes_2020,
                           VEP = sim_Dvotes_2020+sim_Rvotes_2020) %>%
  mutate(pct = (votes/VEP)*100,
         Candidate = "Trump")

biden_elxns_2020 %>% 
  filter(pct > 50) %>% 
  nrow()/100

trump_elxns_2020 %>% 
  filter(pct > 50) %>% 
  nrow()/100

trump_pct <- median(trump_elxns_2020$pct)

biden_pct <- median(biden_elxns_2020$pct)

#together for hist
votes_df <- full_join(biden_elxns_2020, trump_elxns_2020)

#histograms of win margins
votes_df %>% 
  ggplot(aes(x = pct,
             fill = Candidate)) +
  geom_histogram(color = 'white',
                 position = "identity",
                 alpha = .7,
                 bins = 20) +
  scale_fill_manual(values = c("blue2", "red2")) +
  scale_x_continuous(breaks = c(35, 40, 45, 50, 55, 60, 65)) +
  labs(title = "Prediction of National Popular Vote",
       subtitle = "Using historic polling trends and current weighted polls",
       x = "Popular Vote Percentage",
       y = "Count",
       caption = "10,000 binomial process simulations") +
  theme_minimal() +
  theme(plot.title = element_text(face = "bold", size = 20), 
        axis.title.x = element_text(size = 13),
        axis.title.y = element_text(size = 13)) +
  theme(plot.subtitle = element_text(size = 13)) +
  theme(legend.title = element_text(size = 13, face = "bold"),
        legend.text = element_text(size = 10)) +
  theme(plot.caption = element_text(size = 10)) +
    geom_text(aes(x = 39,
            y = 1500, 
            label = "Biden Win: 88.87%\nTrump Win: 11.13%"))

#save plot
ggsave("../figures/national_vote.png", height = 5, width = 7)
```

Iowa, Ohio, Arizona, Texas, North Carolina, Georgia, Florida. 

```{r}
toss_ups <- c("Iowa", "Ohio", "Arizona", "Texas", "North Carolina", "Georgia", "Florida")

gdp2020 <- tibble(year = 2020,
                  quarter = 3,
                  GDP_growth_qt = 33.1)

economy_df <- read_csv("../data/econ.csv") %>% 
  filter(quarter == 3,
         year > 1947) %>% 
  select(year, quarter, GDP_growth_qt)

economy_df <- rbind(economy_df, gdp2020) %>% 
  drop_na()

local_df <- read_csv("../data/local.csv") %>% 
  clean_names() %>% 
  rename(state = state_and_area) %>%
  filter(month < 11) %>% 
  group_by(state, year) %>% 
  summarize(unem_pct = mean(unemployed_prce))

popvotestate_df <- read_csv("../data/popvote_bystate_1948-2016.csv") %>% 
  clean_names()

historic_polls_df <- read_csv("../data/pollavg_bystate_1968-2016.csv")%>% 
  filter(before_convention == FALSE) %>% 
  group_by(candidate_name, state, year) %>% 
  summarize(poll_avg = mean(avg_poll)) %>% 
  rename(candidate = candidate_name) %>% 
  mutate(candidate = case_when(candidate == "George Bush" ~ "Bush, George H.W.",
                               candidate == "George W. Bush" ~ "Bush, George W.",
                               candidate == "Jimmy Carter" ~ "Carter, Jimmy",
                               candidate == "Bill Clinton" ~ "Clinton, Bill",
                               candidate == "Hillary Rodham Clinton" ~ "Clinton, Hillary",
                               candidate == "Bob Dole" ~ "Dole, Robert",
                               candidate == "Michael S. Dukakis" ~ "Dukakis, Michael",
                               candidate == "Gerald R. Ford" ~ "Ford, Gerald",
                               candidate == "Al Gore" ~ "Gore, Al",
                               candidate == "John Kerry" ~ "Kerry, John",
                               candidate == "John McCain" ~ "McCain, John",
                               candidate == "Walter F. Mondale" ~  "Mondale, Walter",
                               candidate == "Barack Obama" ~ "Obama, Barack H.",
                               candidate == "Ronald Reagan" ~ "Reagan, Ronald",
                               candidate == "Mitt Romney" ~ "Romney, Mitt",
                               candidate == "Donald Trump" ~ "Trump, Donald J."))

poll_model_df <- popvotestate_df %>% 
  left_join(popvote_df) %>% 
  left_join(economy_df) %>% 
  left_join(local_df) %>% 
  drop_na(unem_pct) %>% 
  left_join(historic_polls_df) %>% 
  select(year, state, candidate, party, pv, incumbent, incumbent_party, GDP_growth_qt, unem_pct, poll_avg, winner) %>% 
  filter(state %in% toss_ups) %>% 
  drop_na() %>% 
  mutate(incumbent = as.character(incumbent),
         incumbent_party = as.character(incumbent_party))

model_df <- popvotestate_df %>% 
  left_join(popvote_df) %>% 
  left_join(economy_df) %>% 
  left_join(local_df) %>% 
  drop_na(unem_pct) %>% 
  select(year, state, candidate, party, pv, incumbent, incumbent_party, GDP_growth_qt, unem_pct, winner) %>% 
  filter(state %in% toss_ups)
  
```

Model Creation

```{r}

#poll_avg
model_1 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ poll_avg, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 1)

#GDP_growth_qt + party + incumbent + incumbent_party
model_2 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ GDP_growth_qt + party + incumbent + incumbent_party, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 2)

#unem_pct + party + incumbent + incumbent_party
model_3 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ unem_pct + party + incumbent + incumbent_party, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 3)

#poll_avg + party + incumbent + incumbent_party
model_4 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ poll_avg + party + incumbent + incumbent_party, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 4)

#GDP_growth_qt + incumbent + incumbent_party
model_5 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ GDP_growth_qt + incumbent + incumbent_party, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 5)

#unem_pct + incumbent + incumbent_party
model_6 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ unem_pct + incumbent + incumbent_party, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 6)

#poll_avg + incumbent + incumbent_party
model_7 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ poll_avg + incumbent + incumbent_party, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 7)

#GDP_growth_qt + incumbent 
model_8 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ GDP_growth_qt + incumbent, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 8)

#unem_pct + incumbent
model_9 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ unem_pct + incumbent, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 9)

#poll_avg + incumbent
model_10 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ poll_avg + incumbent, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 10)

#GDP_growth_qt + incumbent_party
model_11 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ GDP_growth_qt + incumbent_party, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 11)

#unem_pct + incumbent_party
model_12 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ unem_pct + incumbent_party, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 12)

#poll_avg + incumbent_party
model_13 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ poll_avg + incumbent_party, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 13)

#party + incumbent + incumbent_party + GDP_growth_qt + unem_pct + poll_avg
model_14 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ party + incumbent + incumbent_party + GDP_growth_qt + unem_pct + poll_avg, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 14)

#party + incumbent_party + GDP_growth_qt*incumbent + unem_pct + poll_avg
model_15 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ party + incumbent_party + GDP_growth_qt*incumbent + unem_pct + poll_avg, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 15)

#party + incumbent + GDP_growth_qt*incumbent_party + unem_pct + poll_avg
model_16 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ party + incumbent + GDP_growth_qt*incumbent_party + unem_pct + poll_avg, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 16)

#party + incumbent_party + GDP_growth_qt + unem_pct*incumbent + poll_avg
model_17 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ party + incumbent_party + GDP_growth_qt + unem_pct*incumbent + poll_avg, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 17)

#party + incumbent + GDP_growth_qt + unem_pct*incumbent_party + poll_avg
model_18 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ party + incumbent + GDP_growth_qt + unem_pct*incumbent_party + poll_avg, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 18)

#incumbent_party + GDP_growth_qt*incumbent + unem_pct + poll_avg
model_19 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ incumbent_party + GDP_growth_qt*incumbent + unem_pct + poll_avg, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 19)

#incumbent + GDP_growth_qt*incumbent_party + unem_pct + poll_avg
model_20 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ incumbent + GDP_growth_qt*incumbent_party + unem_pct + poll_avg, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 20)

#incumbent_party + GDP_growth_qt + unem_pct*incumbent + poll_avg
model_21 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ incumbent_party + GDP_growth_qt + unem_pct*incumbent + poll_avg, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 21)

#incumbent + GDP_growth_qt + unem_pct*incumbent_party + poll_avg
model_22 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ incumbent + GDP_growth_qt + unem_pct*incumbent_party + poll_avg, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 22)

#incumbent_party + GDP_growth_qt*incumbent + unem_pct
model_23 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ incumbent_party + GDP_growth_qt*incumbent + unem_pct, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 23)

#incumbent + GDP_growth_qt*incumbent_party + unem_pct
model_24 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ incumbent + GDP_growth_qt*incumbent_party + unem_pct, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 24)

#incumbent_party + GDP_growth_qt + unem_pct*incumbent
model_25 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ incumbent_party + GDP_growth_qt + unem_pct*incumbent, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 25)

#incumbent + GDP_growth_qt + unem_pct*incumbent_party
model_26 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ incumbent + GDP_growth_qt + unem_pct*incumbent_party, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 26)

#GDP_growth_qt*incumbent + unem_pct
model_27 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ GDP_growth_qt*incumbent + unem_pct, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 27)

#GDP_growth_qt*incumbent_party + unem_pct
model_28 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ GDP_growth_qt*incumbent_party + unem_pct, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 28)

#GDP_growth_qt + unem_pct*incumbent
model_29 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ GDP_growth_qt + unem_pct*incumbent, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 29)

#GDP_growth_qt + unem_pct*incumbent_party
model_30 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ GDP_growth_qt + unem_pct*incumbent_party, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 30)

# unem_pct*incumbent_party
model_31 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ unem_pct*incumbent_party, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 31)

# unem_pct*incumbent
model_32 <- poll_model_df %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(model = map(data, ~ train(pv ~ unem_pct*incumbent, 
                 data = .x, method = "lm", trControl = trainControl(method = "LOOCV"))),
         loo = map(model, ~ .x$results),
         rsquared = map(loo, ~ .x$Rsquared),
         rmse = map(loo, ~ .x$RMSE),
         model_no = 32)

models <- rbind(model_1, 
                model_2,
                model_3,
                model_4,
                model_5,
                model_6,
                model_7,
                model_8,
                model_9,
                model_10,
                model_11,
                model_12,
                model_13,
                model_14,
                model_15,
                model_16,
                model_17,
                model_18,
                model_19,
                model_20,
                model_21,
                model_22,
                model_23,
                model_24,
                model_25,
                model_26,
                model_27,
                model_28,
                model_29,
                model_30,
                model_31,
                model_32)

#Ends up with Florida 4 Arizona 4 Georgia 12 Ohio 1 North Carolina 9 Iowa 9 Texas 9 
#1 and 4 are just poll based
#9 and 12 unemployment based

models <- models %>% 
  mutate(rsquared = as.numeric(rsquared),
         rmse = as.numeric(rmse),
         out = rsquared/rmse) %>%
  group_by(state) %>% 
  top_n(1, out)

fl_df <- poll_model_df %>% 
  filter(state == "Florida")
fl_mod <- train(pv ~ poll_avg + party + incumbent + incumbent_party, 
        data = fl_df, method = "lm", trControl = trainControl(method = "LOOCV"))

az_df <- poll_model_df %>% 
  filter(state == "Arizona")
az_mod <- train(pv ~ poll_avg + party + incumbent + incumbent_party, 
        data = az_df, method = "lm", trControl = trainControl(method = "LOOCV"))

ga_df <- poll_model_df %>% 
  filter(state == "Georgia")
ga_mod <- train(pv ~ unem_pct + incumbent_party, 
                 data = ga_df, method = "lm", trControl = trainControl(method = "LOOCV"))

oh_df <- poll_model_df %>% 
  filter(state == "Ohio")
oh_mod <- train(pv ~ poll_avg, 
      data = oh_df, method = "lm", trControl = trainControl(method = "LOOCV"))

nc_df <- poll_model_df %>% 
  filter(state == "North Carolina")
nc_mod <- train(pv ~ unem_pct + incumbent, 
                 data = nc_df, method = "lm", trControl = trainControl(method = "LOOCV"))

ia_df <- poll_model_df %>% 
  filter(state == "Iowa")
ia_mod <- train(pv ~ unem_pct + incumbent, 
                 data = ia_df, method = "lm", trControl = trainControl(method = "LOOCV"))

tx_df <- poll_model_df %>% 
  filter(state == "Texas")
tx_mod <- train(pv ~ unem_pct + incumbent, 
                 data = tx_df, method = "lm", trControl = trainControl(method = "LOOCV"))


  

  

model_outputs <- export_summs(fl_mod$finalModel, az_mod$finalModel, ga_mod$finalModel, 
                              oh_mod$finalModel, nc_mod$finalModel, ia_mod$finalModel, tx_mod$finalModel,
                              model.names = c("Florida","Arizona","Georgia", "Ohio", "North Carolina", "Iowa", "Texas"),
                              coefs = c("Intercept" = "(Intercept)",
                       "Average Poll" = "poll_avg",
                       "Republican" = "partyrepublican",
                       "Incumbent" = "incumbentTRUE",
                       "Incumbent Party" = "incumbent_partyTRUE",
                       "Unemployment Rate" = "unem_pct"),
                       statistics = NULL)


models <- models %>% 
  select(state, rsquared, rmse)

models <- tibble(models)

models %>% 
  gt() %>% 
  tab_header(title = md("**In and Out of Sample Validation**")) %>%
  cols_label(
    state = md("**State**"),
    rsquared = md("**R-Squared**"),
    rmse = md("**RMSE**"))
```

```{r}
toss_pred_df <- poll_pred %>% 
  filter(state %in% toss_ups) %>% 
  mutate(poll_avg = mean,
         party = if_else(answer == "Biden", "democrat", "republican"),
         incumbent = if_else(answer == "Biden", "FALSE", "TRUE"),
         incumbent_party = if_else(answer == "Biden", "FALSE", "TRUE"),
         year = 2020) %>% 
  left_join(local_df)

fl_pred <- tibble(pred = predict.train(object = fl_mod, newdata = (toss_pred_df %>% filter(state == "Florida"))),
                  answer = c("Biden", "Trump")) %>% 
  mutate(state = "Florida")
az_pred <- tibble(pred = predict.train(object = az_mod, newdata = (toss_pred_df %>% filter(state == "Arizona"))),
                  answer = c("Biden", "Trump")) %>% 
                    mutate(state = "Arizona")
ga_pred <- tibble(pred = predict.train(object = ga_mod, newdata = (toss_pred_df %>% filter(state == "Georgia"))),
                  answer = c("Biden", "Trump")) %>% 
                  mutate(state = "Georgia")
oh_pred <- tibble(pred = predict.train(object = oh_mod, newdata = (toss_pred_df %>% filter(state == "Ohio"))),
                  answer = c("Biden", "Trump")) %>% 
                  mutate(state = "Ohio") 
ia_pred <- tibble(pred = predict.train(object = ia_mod, newdata = (toss_pred_df %>% filter(state == "Iowa"))),
                  answer = c("Biden", "Trump")) %>% 
                  mutate(state = "Iowa")

nc_pred <- tibble(pred = predict.train(object = nc_mod, newdata = (toss_pred_df %>% filter(state == "North Carolina"))),
                  answer = c("Biden", "Trump")) %>% 
                  mutate(state = "North Carolina")

tx_pred <- tibble(pred = predict.train(object = tx_mod, newdata = (toss_pred_df %>% filter(state == "Texas"))),
                  answer = c("Biden", "Trump")) %>% 
                  mutate(state = "Texas")

toss_preds <- rbind(tx_pred, nc_pred, ia_pred, oh_pred, ga_pred, az_pred,fl_pred)

toss_pred_df <- toss_pred_df %>% 
  left_join(toss_preds, by = c("state", "answer")) %>% 
  mutate(new_pred = (mean + pred)/2)
```

Win margin plot

```{r}
trump_toss_pred_df <- toss_pred_df %>% 
  filter(answer == "Trump") %>% 
  select(state, new_pred) %>% 
  rename(mean = new_pred)

biden_toss_pred_df <- toss_pred_df %>% 
  filter(answer == "Biden") %>% 
  select(state, new_pred)  %>% 
  rename(mean = new_pred)

final_toss_df <- trump_toss_pred_df %>% 
  left_join(biden_toss_pred_df,
            by = "state",
            suffix = c("_trump", "_biden")) %>% 
  select(-answer_trump, -answer_biden) %>% 
  mutate(dif_trump = mean_trump - mean_biden)

main_final_estimate_df <- wide_poll_pred %>% 
  filter(!is.na(state),
         map != "Toss-Up") %>% 
  select(-map)

final_estimate_df <- rbind(final_toss_df, main_final_estimate_df) %>% 
  mutate(map = case_when(dif_trump > 10 ~ "Solid Trump",
                         dif_trump > 0 & dif_trump < 10 ~ "Lean Trump",
                         dif_trump < -10 ~ "Solid Biden",
                         dif_trump < 0 & dif_trump > -10 ~ "Lean Biden")) %>% 
  mutate(map = factor(map, levels = c("Solid Trump", "Lean Trump", "Lean Biden", "Solid Biden")))

model_trump_toss_pred_df <- toss_pred_df %>% 
  filter(answer == "Trump") %>% 
  select(state, pred) %>% 
  rename(mean = pred)

model_biden_toss_pred_df <- toss_pred_df %>% 
  filter(answer == "Biden") %>% 
  select(state, pred)  %>% 
  rename(mean = pred)

model_final_toss_df <- model_trump_toss_pred_df %>% 
  left_join(model_biden_toss_pred_df,
            by = "state",
            suffix = c("_trump", "_biden")) %>% 
  select(-answer_trump, -answer_biden) %>% 
  mutate(dif_trump = mean_trump - mean_biden)

model_estimate_df <- rbind(model_final_toss_df, main_final_estimate_df) %>% 
   mutate(map = case_when(dif_trump > 10 ~ "Solid Trump",
                         dif_trump > 0 & dif_trump < 10 ~ "Lean Trump",
                         dif_trump < -10 ~ "Solid Biden",
                         dif_trump < 0 & dif_trump > -10 ~ "Lean Biden")) %>% 
  mutate(map = factor(map, levels = c("Solid Trump", "Lean Trump", "Lean Biden", "Solid Biden")))




```

maps of final estimates

```{r}
#map based upon factor columns 
plot_usmap(data = model_estimate_df, regions = "states", values = "map", color = "black") +
  scale_fill_manual(values = c("red4","red", "blue","blue4"), name = "Election Outcome") +
  labs(title = "2020 Presidential Election Prediction",
       subtitle = " Model-based prediciton for toss-up states") +
  theme_void() +
  theme(plot.title = element_text(face = "bold", size = 20)) +
  theme(plot.subtitle = element_text(size = 15),
        strip.text = element_text(colour = 'black')) +
   theme(legend.title = element_text(size = 13, face = "bold"),
        legend.text = element_text(size = 11))

ggsave("../figures/final_models_plot.png", height = 4.5)

#map based upon factor columns 
plot_usmap(data = final_estimate_df, regions = "states", values = "map", color = "black") +
  scale_fill_manual(values = c("red4","red", "blue","blue4"), name = "Election Outcome") +
  labs(title = "2020 Presidential Election Prediction",
       subtitle = " Poll and model-based prediciton for toss-up states") +
  theme_void() +
  theme(plot.title = element_text(face = "bold", size = 20)) +
  theme(plot.subtitle = element_text(size = 15),
        strip.text = element_text(colour = 'black')) +
   theme(legend.title = element_text(size = 13, face = "bold"),
        legend.text = element_text(size = 11))

ggsave("../figures/final_estimate_plot.png", height = 4.5)

```

Electoral College

```{r}
ec_polls_df <- pred_df %>% 
  drop_na(state)

#replicate rows for weights
#https://stackoverflow.com/questions/38499032/repeat-the-rows-in-a-data-frame-based-on-values-in-a-specific-column
ec_polls_df <- ec_polls_df[rep(seq(nrow(ec_polls_df)), ec_polls_df$weight),]
#sd of .109 for both Biden and Trump from earlier

vep_df <- read_csv("../data/vep_1980-2016.csv") %>% 
  filter(state != "United States")

pvstate_df <- read_csv("../data/popvote_bystate_1948-2016.csv") %>% 
  filter(year > 1967)

popvote_df <- read_csv("../data/popvote_1948-2016.csv")

historic_polls_df <- historic_polls_df %>% 
  drop_na()

ec_poll_vep_df <- pvstate_df %>% 
  inner_join(vep_df) %>% 
  left_join(popvote_df) %>% 
  inner_join(historic_polls_df) %>% 
  drop_na() %>% 
  group_by(state) %>% 
  nest() %>%
  rename(ec_poll_vep = data)

ec_dist_df <- ec_polls_df %>% 
  group_by(state) %>% 
  nest() %>% 
  rename(state_data20 = data) %>% 
  left_join(vep_df %>% filter(year == 2016)) %>% 
  select(-year, -VAP) %>% 
  left_join(ec_poll_vep_df) %>% 
  mutate(republican_r = map(ec_poll_vep, ~ filter(., party == "republican")),
         republican_r = map(republican_r, ~ mutate(., prob_poll = poll_avg/100))) %>% 
  mutate(democrat_d = map(ec_poll_vep, ~ filter(., party == "democrat")),
         democrat_d = map(democrat_d, ~ mutate(., prob_poll = poll_avg/100))) %>% 
    mutate(sd_r = map(republican_r, ~ sd(.$prob_poll))) %>% 
  mutate(sd_d = map(democrat_d, ~ sd(.$prob_poll))) %>% 
  mutate(r_glm = map(republican_r, ~ glm(cbind(R, VEP-R) ~ poll_avg, .x , family = binomial)),
         d_glm = map(democrat_d, ~ glm(cbind(D, VEP-D) ~ poll_avg, .x , family = binomial))) %>% 
  left_join(final_estimate_df) %>% 
  select(state, VEP, r_glm, d_glm, sd_r, sd_d, mean_trump, mean_biden) %>% 
  group_by(state) %>% 
  nest() %>%
  mutate(prob_Rvote_2020 = map(data, ~ predict(.$r_glm, newdata = data.frame(poll_avg = .$mean_trump), type="response")[[1]])) %>% 
  mutate(prob_Dvote_2020 = map(data, ~ predict(.$d_glm, newdata = data.frame(poll_avg = .$mean_biden), type="response")[[1]])) %>% 
  unnest() %>%
  group_by(state) %>% 
  mutate(r_prob = rnorm(1000, mean = prob_Rvote_2020, sd = sd_r)))

  nest() %>% 
  ungroup() %>% 
  mutate(r_prob = map(data, ~ rnorm(1000, mean = .x$prob_Rvote_2020, sd = .x$sd_r)))


  mutate(sim_Rvotes_2020 = map_df(data, ~ rbinom(n = 1000, size = as.integer(.$VEP), prob = rnorm(1000, mean = .$prob_Rvote_2020, sd = .$sd_r))))
                               
?map_df
                               
sim_Dvotes_2020 <- rbinom(n = 10000, size = VEP, prob = rnorm(10000, mean = prob_Dvote_2020, sd = SD_D))

## Simulating a distribution of election results
biden_elxns_2020 <- tibble(votes = sim_Dvotes_2020,
                           VEP = sim_Dvotes_2020+sim_Rvotes_2020) %>%
  mutate(pct = (votes/VEP)*100,
         Candidate = "Biden")

trump_elxns_2020 <- tibble(votes = sim_Rvotes_2020,
                           VEP = sim_Dvotes_2020+sim_Rvotes_2020) %>%
  mutate(pct = (votes/VEP)*100,
         Candidate = "Trump")

biden_elxns_2020 %>% 
  filter(pct > 50) %>% 
  nrow()/100

trump_elxns_2020 %>% 
  filter(pct > 50) %>% 
  nrow()/100

trump_pct <- median(trump_elxns_2020$pct)

biden_pct <- median(biden_elxns_2020$pct)

#together for hist
votes_df <- full_join(biden_elxns_2020, trump_elxns_2020)

#histograms of win margins
votes_df %>% 
  ggplot(aes(x = pct,
             fill = Candidate)) +
  geom_histogram(color = 'white',
                 position = "identity",
                 alpha = .7,
                 bins = 20) +
  scale_fill_manual(values = c("blue2", "red2")) +
  scale_x_continuous(breaks = c(35, 40, 45, 50, 55, 60, 65)) +
  labs(title = "Prediction of National Popular Vote",
       subtitle = "Using historic polling trends and current weighted polls",
       x = "Popular Vote Percentage",
       y = "Count",
       caption = "10,000 binomial process simulations") +
  theme_minimal() +
  theme(plot.title = element_text(face = "bold", size = 20), 
        axis.title.x = element_text(size = 13),
        axis.title.y = element_text(size = 13)) +
  theme(plot.subtitle = element_text(size = 13)) +
  theme(legend.title = element_text(size = 13, face = "bold"),
        legend.text = element_text(size = 10)) +
  theme(plot.caption = element_text(size = 10)) +
    geom_text(aes(x = 39,
            y = 1500, 
            label = "Biden Win: 88.87%\nTrump Win: 11.13%"))

#save plot
ggsave("../figures/national_vote.png", height = 5, width = 7)
```



